### PR TITLE
Allow temp functions to also be run setup_file and teardown_file

### LINKED ISSUE #35: Failure to run `temp_make` in the `setup_file` block.
I require some common setup for all test cases in a file, but am not able to run `make_temp` inside the `setup_file` block.

```bats
setup_file() {
    TEMP_REPO_NOTAG="$(temp_make)"
}
```

```output
 ✗
   (from function `setup_file' in test file test/bump_semver.bats, line 9)
     `TEMP_REPO_NOTAG="$(temp_make)"' failed

   -- ERROR: temp_make --
   Must be called from `setup', `@test' or `teardown'
   --

   bats warning: Executed 1 instead of expected 8 tests

8 tests, 1 failure, 7 not run
```

Would you consider allowing this?

### PR DESCRIPTION
**Pull request by NickLarsenNZ**
Allow temp_make and temp_del to be run in setup_file and teardown_file

Fixes #35

### CODE REVIEW

**Comment by NickLarsenNZ** [comment]
I'm just adding tests now

**Comment by NickLarsenNZ** [comment]
I've just followed the existing pattern, but might need someone more familiar with `bats-file` to take a closer look.
Also, looks like the tests fail for reasons mentioned in #31

**Comment by jlisee** [comment]
@NickLarsenNZ I would love this fix, do you think you could get the CI build passing?

**Comment by NickLarsenNZ** [comment]
Hi @jlisee, I took a look at the issue I linked above and it is still open and unresolved.

When I'm at my laptop I'll rebase and check. Maybe I'll look at the cause of the test failures and try to resolve the other ticket before progressing this one.

**Comment by NickLarsenNZ** [comment]
I had a quick look at the existing CI issues and I wonder if it's a problem with `batslib_is_caller` from over in http://github.com/bats-core/bats-support.

Maybe @sublimino might know?
Maybe in the meantime those tests can be skipped so PRs can progress. In saying that, it looks like there's not a lot of movement on this repo judging by the length of time the open PRs have been sitting here.

**Comment by martin-schulze-vireso** [comment]
I rebased onto current master to get the CI fixes in.

**Review by martin-schulze-vireso — APPROVED** [review]

**Comment by martin-schulze-vireso** [comment]
Thanks for your PR.

**Pull request merged**
