### PR TITLE
Enable extended regex in assert_file_contains

### PR DESCRIPTION
**Pull request by dsbibby**
Enables use of extended regex patterns in the `assert_file_contains` function

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
Will this Change the behavior of existing code?

**Comment by dsbibby** [comment]
From my research, I don't think it would, however I have changed the PR to add an optional 3rd argument to allow specifying the grep command to use (either `grep`, `egrep`, or `pcregrep`). `grep` is the default.

Let me know what you think.

**Review by martin-schulze-vireso — APPROVED** [review]

**Comment by martin-schulze-vireso** [comment]
I tried to fix some issues with the code but cannot push over your code. Can you [allow maintainers to push](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

**Comment by dsbibby** [comment]
Apologies, I accidentally hit the request review button!

I would happily enable this however I can't see the option to allow edits by maintainers for some reason.

I notice I didn't sign my last commit - is this the only issue? If so I'll correct that now.

**Comment by martin-schulze-vireso** [comment]
I think the problem is that your @dsbibby account is not the same as the repos (@pilue). I have reworked the code a bit. See if you can incorporate the changes in https://github.com/bats-core/bats-file/tree/pr/dsbibby/46

**Comment by martin-schulze-vireso** [comment]
Closed in favor of #63

**Pull request closed without merging**
