### PR TITLE
feat: adds the missing assert_file_not_contains function

### PR DESCRIPTION
**Pull request by artis3n**
I needed to use this method and I noticed the open issue that it does not yet exist. Added the `assert_file_not_contains` method and tests that are basically just the exact opposities of the `assert_file_contains` tests.

### CODE REVIEW

**Review by martin-schulze-vireso — COMMENTED** [review]
Thanks for this PR. Please add a test for wäre the File does not exist and document the desired behavior.

**Comment by artis3n** [comment]
@martin-schulze-vireso That isn't a test that exists for `assert_file_contains`, and seems to reproduce the work that `assert_file_exists` does, no?

I have a local `@test 'assert_file_not_contains() <file>: returns 1 and displays path if <file> does not exist'` test, but given the way `assert_file_contains` is written (which I mirrored in `assert_file_not_contains`), it returns exit code 0 alongside a grep error about the file not existing.

image

image

Do you want me to rewrite both `assert_file_contains` and `assert_file_not_contains` entirely to handle missing file cases? I'd prefer an expectation that an end user runs the `assert_file_exists` check in their test.

**Comment by artis3n** [comment]
Got it, that makes sense. Would you prefer I invoke `assert_file_exists` from the `assert_file_not_contains` function, duplicate the existence check code, or do something else?

**Comment by martin-schulze-vireso** [comment]
You can call it if the resulting backtrace still points to the call to assert_file_not_contains.

**Comment by artis3n** [comment]
What do you think of these changes?

**Comment by artis3n** [comment]
On the failed test - `macos-10.15` isn't a [supported runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) anymore. Would you like me to bump that to `macos-12`?

**Comment by artis3n** [comment]
Done!

**Review by martin-schulze-vireso — APPROVED** [review]

**Comment by martin-schulze-vireso** [comment]
Please sign your commits, this is the last missing step.

**Comment by artis3n** [comment]
Done!

**Comment by martin-schulze-vireso** [comment]
Thanks for your contribution(and patience).

**Pull request merged**
