### PR TITLE
temp.bash: Remove executable bit

### PR DESCRIPTION
**Pull request by gioele**
Bats libraries are not meant to be executed as standalone files.

### CODE REVIEW

**Review by martin-schulze-vireso — APPROVED** [review]

**Comment by gioele** [comment]
Hi @martin-schulze-vireso, could you please merge this and the other approved PRs?

It would make it easier to include these fixes in the `bats-file` Debian package in time for the Bookworm freeze (the deadline is in a few days).

**Comment by martin-schulze-vireso** [comment]
The others are not mergable and I cant See why from my phone.

**Comment by gioele** [comment]
I signed the commits in #53 and #54. Both PRs should now be mergeable via GitHub.

(The settings for `bats-file` seem to require signed commits...)

**Comment by martin-schulze-vireso** [comment]
Yes, thanks for fixing and thanks for your contributions.

**Comment by martin-schulze-vireso** [comment]
@gioele seeing your recent work, would you be interested in becoming a maintainer for bats-file?

**Comment by gioele** [comment]
@martin-schulze-vireso thanks for the opportunity! Unfortunately at the moment I don't have enough spare volunteer time for helping with the maintainership of bats-file.

**Comment by martin-schulze-vireso** [comment]
Thank you for responding. I totally understand and already expected this, considering your vitae. Thanks again for your contributions.

**Pull request merged**
